// SEED GENERATOR (inline version): same output as generate-user-seed.ts, but every
// field is generated right here with faker instead of going through UserBuilder.
//
//   npx tsx scripts/generate-user-seed-inline.ts --role COMMISSIONER --count 3 \
//     --out db/changelog/changes/902-seed-commissioners.sql
//
// Generate once and commit the file. Never regenerate a changeset that has already
// run: the password salt is random, so the SQL (and its checksum) changes every time.
import { writeFileSync } from 'node:fs';
import { parseArgs } from 'node:util';
import { faker, fakerTH } from '@faker-js/faker';
import { hashPassword } from '../src/auth/passwords';
import { Role } from '../src/domain/types';

const ROLES: Role[] = ['VOTER', 'COMMISSIONER', 'ADMIN'];

const { values: args } = parseArgs({
  options: {
    role: { type: 'string', default: 'COMMISSIONER' },
    count: { type: 'string', default: '3' },
    district: { type: 'string', default: 'CM-1' },
    password: { type: 'string', default: 'password123' },
    seed: { type: 'string', default: '20261003' },
    context: { type: 'string', default: 'dev' },
    id: { type: 'string' },
    out: { type: 'string' },
  },
});

const role = args.role.toUpperCase() as Role;
if (!ROLES.includes(role)) throw new Error(`--role must be one of ${ROLES.join(', ')}`);

const count = Number(args.count);
if (!Number.isInteger(count) || count < 1) throw new Error('--count must be a positive integer');

// The password is recorded in the file header (like 900/901), so never generate for a real environment.
const SEED_CONTEXTS = ['dev', 'e2e'];
if (!SEED_CONTEXTS.includes(args.context)) {
  throw new Error(`--context must be one of ${SEED_CONTEXTS.join(', ')} — seed accounts have known passwords`);
}

const changesetId = args.id ?? `902-seed-${role.toLowerCase()}s`;

// Same seed → same names and national ids, so the file is reproducible and reviewable.
faker.seed(Number(args.seed));
fakerTH.seed(Number(args.seed));

// scrypt is slow on purpose — hash once and share it across all generated users.
const passwordHash = hashPassword(args.password);

interface SeedUser {
  nationalId: string;
  firstName: string;
  lastName: string;
  address: string;
}

const users: SeedUser[] = [];
const seen = new Set<string>();
while (users.length < count) {
  // Thai national id: 12 random digits + checksum digit (weights 13..2, mod 11).
  const base = faker.string.numeric({ length: 12, allowLeadingZeros: false });
  const sum = [...base].reduce((acc, digit, i) => acc + Number(digit) * (13 - i), 0);
  const nationalId = base + ((11 - (sum % 11)) % 10);

  const user: SeedUser = {
    nationalId,
    firstName: fakerTH.person.firstName(),
    lastName: fakerTH.person.lastName(),
    address: fakerTH.location.streetAddress(),
  };

  if (seen.has(user.nationalId)) continue;
  seen.add(user.nationalId);
  users.push(user);
}

const sql = (value: string) => `'${value.replaceAll("'", "''")}'`;

const rows = users.map(
  (u) =>
    `    (${[u.nationalId, passwordHash, u.firstName, u.lastName, u.address, args.district, role]
      .map(sql)
      .join(', ')})`,
);
const nationalIds = users.map((u) => sql(u.nationalId)).join(',');

const output = `--liquibase formatted sql

-- Generated by scripts/generate-user-seed-inline.ts — do not edit by hand.
--   --role ${role} --count ${count} --district ${args.district} --seed ${args.seed} --context ${args.context}
--
-- Accounts (national id / password ${args.password}):
${users.map((u) => `--   ${u.nationalId}  ${u.firstName} ${u.lastName}`).join('\n')}

--changeset election:${changesetId} context:${args.context}
INSERT INTO users (national_id, password_hash, first_name, last_name, address, district_id, role) VALUES
${rows.join(',\n')};
--rollback DELETE FROM users WHERE national_id IN (${nationalIds});
`;

if (args.out) {
  writeFileSync(args.out, output);
  console.error(`wrote ${users.length} ${role} user(s) to ${args.out}`);
} else {
  process.stdout.write(output);
}
